spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS = false

oanda.account.id=xxxx
oanda.rest.header.authentication=xxxx

strader76.strategy.test=true
strader76.websocket.topic=/topic/candlestick
strader76.websocket.test.topic=/topic/test/candlestick

strader76.websocket.topic.positions=/topic/positions
strader76.websocket.test.topic.positions=/topic/positions
